# -*- coding: utf-8 -*-
"""PRO-C103: DATA VISUALISATION

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j96W50ZbTzIktLtiWjUZ1EtOIMVG-VNg
"""

from google.colab import files
dataToLoad=files.upload()

import pandas as pd

df=pd.read_csv('Copy+of+data+-+data.csv')
print(df)

import plotly.express as px
fig=px.scatter(df,x='date',y='cases',color='country',title='Covid data for different countries')
fig.show()